---

# This is the ssh user you use from the control machine to the target machine
ansible_user: root

# We are using the community repo
repo: https://github.com/EOSIO/eos
version: v1.3.0

# A simple reference, it doesnt have to be a producer name
agent_name: add_your_name

# The user to create which will run nodeos
ops_user: eos

# Override the default install locations
eos_install_dir: /opt/eos
mainnet_install_dir: /opt/mainnet

# Use these settings for non standard ssh port and/or ssh key
# ansible_ssh_private_key_file: ~/.ssh/key.pem
# ansible_port: 4567