---

- import_tasks: requirements.yml

- name: Install eos
  apt:
    deb: "{{ eos_deb }}"

- name: Disable timedatectl
  shell: timedatectl set-ntp no
  tags:
    - time

- name: Make sure ntp is installed
  apt: name=ntp state=installed
  tags:
    - time

- name: Add specific ops user
  user:
    name: "{{ ops_user }}"
    shell: /bin/bash
    groups: sudo
    state: present
    home: "/home/{{ ops_user }}"